In [100]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

In [101]:
pd.options.display.max_columns=None

In [102]:
df=pd.read_csv("credit_score_updated.csv")

In [103]:
df.head()

,Customer ID,INCOME,SAVINGS,DEBT,CLOTHING,EDUCATION,ENTERTAINMENT,FINES,GAMBLING,GROCERIES,HEALTH,HOUSING,TAX,TRAVEL,UTILITIES,EXPENDITURE,CAT_GAMBLING,CAT_DEBT,CAT_CREDIT_CARD,CAT_MORTGAGE,CAT_SAVINGS_ACCOUNT,CAT_DEPENDENTS,CREDIT_SCORE,DEFAULT
0,C02COQEVYU,"$33,269.00",$-,"$532,304.00","$1,889.00",$-,"$3,068.00",$-,"$1,313.00","$4,849.00",$320.00,"$3,006.00",$-,"$17,893.00",$931.00,"$33,269.00",High,1,0,0,0,0,444,1
1,C02OZKC0ZF,"$77,158.00","$91,187.00","$315,648.00","$5,818.00",$-,"$17,244.00",$-,$-,"$5,224.00",$467.00,"$16,339.00","$1,973.00","$20,234.00","$2,845.00","$70,144.00",No,1,0,0,1,0,625,0
2,C03FHP2D0A,"$30,917.00","$21,642.00","$534,864.00","$1,157.00",$-,"$3,611.00",$36.00,"$1,201.00","$4,335.00",$891.00,"$2,759.00",$-,"$16,072.00",$855.00,"$30,917.00",High,1,0,0,1,0,469,1
3,C03PVPPHOY,"$80,657.00","$64,526.00","$629,125.00","$6,857.00","$4,402.00","$13,446.00",$-,"$7,796.00","$4,547.00","$2,068.00","$12,619.00","$1,675.00","$25,038.00","$2,209.00","$80,657.00",High,1,0,0,1,0,559,0
4,C04J69MUX0,"$149,971.00","$1,172,498.00","$2,399,531.00","$1,978.00",$-,"$5,194.00",$-,"$1,734.00","$34,814.00","$7,513.00","$42,658.00","$3,941.00","$28,167.00","$10,338.00","$136,337.00",High,1,1,1,1,1,473,0

In [104]:
columns_to_check=["INCOME","SAVINGS","DEBT","CLOTHING","EDUCATION","ENTERTAINMENT","FINES","GAMBLING","GROCERIES","HEALTH","HOUSING","TAX","TRAVEL","UTILITIES","EXPENDITURE"]

In [105]:
df.columns.tolist()

['Customer ID',
 ' INCOME ',
 ' SAVINGS ',
 ' DEBT ',
 ' CLOTHING  ',
 ' EDUCATION ',
 ' ENTERTAINMENT ',
 ' FINES ',
 ' GAMBLING ',
 ' GROCERIES ',
 ' HEALTH ',
 ' HOUSING ',
 ' TAX ',
 ' TRAVEL ',
 ' UTILITIES ',
 ' EXPENDITURE ',
 ' CAT_GAMBLING ',
 'CAT_DEBT',
 'CAT_CREDIT_CARD',
 'CAT_MORTGAGE',
 'CAT_SAVINGS_ACCOUNT',
 'CAT_DEPENDENTS',
 'CREDIT_SCORE',
 'DEFAULT']

In [106]:
df.columns=df.columns.str.strip()

In [107]:
df["GAMBLING"].dtype

dtype('O')

In [108]:
for column in columns_to_check:
    df[column] = df[column].replace({'\$':''}, regex = True)

In [109]:
df.head()

,Customer ID,INCOME,SAVINGS,DEBT,CLOTHING,EDUCATION,ENTERTAINMENT,FINES,GAMBLING,GROCERIES,HEALTH,HOUSING,TAX,TRAVEL,UTILITIES,EXPENDITURE,CAT_GAMBLING,CAT_DEBT,CAT_CREDIT_CARD,CAT_MORTGAGE,CAT_SAVINGS_ACCOUNT,CAT_DEPENDENTS,CREDIT_SCORE,DEFAULT
0,C02COQEVYU,"33,269.00",-,"532,304.00","1,889.00",-,"3,068.00",-,"1,313.00","4,849.00",320.00,"3,006.00",-,"17,893.00",931.00,"33,269.00",High,1,0,0,0,0,444,1
1,C02OZKC0ZF,"77,158.00","91,187.00","315,648.00","5,818.00",-,"17,244.00",-,-,"5,224.00",467.00,"16,339.00","1,973.00","20,234.00","2,845.00","70,144.00",No,1,0,0,1,0,625,0
2,C03FHP2D0A,"30,917.00","21,642.00","534,864.00","1,157.00",-,"3,611.00",36.00,"1,201.00","4,335.00",891.00,"2,759.00",-,"16,072.00",855.00,"30,917.00",High,1,0,0,1,0,469,1
3,C03PVPPHOY,"80,657.00","64,526.00","629,125.00","6,857.00","4,402.00","13,446.00",-,"7,796.00","4,547.00","2,068.00","12,619.00","1,675.00","25,038.00","2,209.00","80,657.00",High,1,0,0,1,0,559,0
4,C04J69MUX0,"149,971.00","1,172,498.00","2,399,531.00","1,978.00",-,"5,194.00",-,"1,734.00","34,814.00","7,513.00","42,658.00","3,941.00","28,167.00","10,338.00","136,337.00",High,1,1,1,1,1,473,0

In [110]:
for column in columns_to_check:
    df[column] = df[column].replace({'-':'0'}, regex = True)

In [111]:
df.head(100)

,Customer ID,INCOME,SAVINGS,DEBT,CLOTHING,EDUCATION,ENTERTAINMENT,FINES,GAMBLING,GROCERIES,HEALTH,HOUSING,TAX,TRAVEL,UTILITIES,EXPENDITURE,CAT_GAMBLING,CAT_DEBT,CAT_CREDIT_CARD,CAT_MORTGAGE,CAT_SAVINGS_ACCOUNT,CAT_DEPENDENTS,CREDIT_SCORE,DEFAULT
0,C02COQEVYU,"33,269.00",0,"532,304.00","1,889.00",0,"3,068.00",0,"1,313.00","4,849.00",320.00,"3,006.00",0,"17,893.00",931.00,"33,269.00",High,1,0,0,0,0,444,1
1,C02OZKC0ZF,"77,158.00","91,187.00","315,648.00","5,818.00",0,"17,244.00",0,0,"5,224.00",467.00,"16,339.00","1,973.00","20,234.00","2,845.00","70,144.00",No,1,0,0,1,0,625,0
2,C03FHP2D0A,"30,917.00","21,642.00","534,864.00","1,157.00",0,"3,611.00",36.00,"1,201.00","4,335.00",891.00,"2,759.00",0,"16,072.00",855.00,"30,917.00",High,1,0,0,1,0,469,1
3,C03PVPPHOY,"80,657.00","64,526.00","629,125.00","6,857.00","4,402.00","13,446.00",0,"7,796.00","4,547.00","2,068.00","12,619.00","1,675.00","25,038.00","2,209.00","80,657.00",High,1,0,0,1,0,559,0
4,C04J69MUX0,"149,971.00","1,172,498.00","2,399,531.00","1,978.00",0,"5,194.00",0,"1,734.00","34,814.00","7,513.00","42,658.00","3,941.00","28,167.00","10,338.00","136,337.00",High,1,1,1,1,1,473,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,C3TS8Y4O0V,"88,276.00","105,931.00","635,587.00","8,884.00",0,"17,509.00",0,"8,606.00","5,914.00","1,727.00",0,"2,180.00","40,585.00","2,871.00","88,276.00",High,1,0,0,1,0,564,0
96,C3UCLV7RVH,"123,364.00","185,046.00","1,122,612.00","4,577.00",0,"35,005.00",0,0,"10,607.00","4,622.00",0,"3,829.00","59,699.00","5,025.00","123,364.00",No,1,0,0,1,0,535,0
97,C3UTGPU7LW,"64,249.00","147,773.00","1,278,555.00","1,857.00","10,413.00","2,783.00",0,928.00,"21,343.00","5,286.00",0,"2,289.00","13,856.00","5,494.00","64,249.00",Low,1,1,0,1,1,447,1
98,C3VO9SYOW6,"174,117.00","411,549.00","2,311,005.00","7,020.00","5,367.00","20,297.00",0,0,"20,203.00","6,062.00","28,903.00","8,931.00","50,785.00","10,720.00","158,288.00",No,1,1,0,1,0,552,0
99,C41ADEN33W,"113,584.00","435,404.00","870,808.00","4,820.00",0,"21,597.00",0,"8,523.00","16,318.00","4,867.00","23,308.00","6,602.00",0,"8,618.00","94,653.00",High,1,1,0,1,0,541,1

In [112]:
for column in columns_to_check:
    df[column] = df[column].replace({'\.':''}, regex = True)
    df[column] = df[column].replace({',':''}, regex = True)

In [113]:
df.head()

,Customer ID,INCOME,SAVINGS,DEBT,CLOTHING,EDUCATION,ENTERTAINMENT,FINES,GAMBLING,GROCERIES,HEALTH,HOUSING,TAX,TRAVEL,UTILITIES,EXPENDITURE,CAT_GAMBLING,CAT_DEBT,CAT_CREDIT_CARD,CAT_MORTGAGE,CAT_SAVINGS_ACCOUNT,CAT_DEPENDENTS,CREDIT_SCORE,DEFAULT
0,C02COQEVYU,3326900,0,53230400,188900,0,306800,0,131300,484900,32000,300600,0,1789300,93100,3326900,High,1,0,0,0,0,444,1
1,C02OZKC0ZF,7715800,9118700,31564800,581800,0,1724400,0,0,522400,46700,1633900,197300,2023400,284500,7014400,No,1,0,0,1,0,625,0
2,C03FHP2D0A,3091700,2164200,53486400,115700,0,361100,3600,120100,433500,89100,275900,0,1607200,85500,3091700,High,1,0,0,1,0,469,1
3,C03PVPPHOY,8065700,6452600,62912500,685700,440200,1344600,0,779600,454700,206800,1261900,167500,2503800,220900,8065700,High,1,0,0,1,0,559,0
4,C04J69MUX0,14997100,117249800,239953100,197800,0,519400,0,173400,3481400,751300,4265800,394100,2816700,1033800,13633700,High,1,1,1,1,1,473,0

In [114]:
for column in columns_to_check:
    df[column] = pd.to_numeric(df[column])
    df[column] = df[column]/100

In [115]:
df.head()

,Customer ID,INCOME,SAVINGS,DEBT,CLOTHING,EDUCATION,ENTERTAINMENT,FINES,GAMBLING,GROCERIES,HEALTH,HOUSING,TAX,TRAVEL,UTILITIES,EXPENDITURE,CAT_GAMBLING,CAT_DEBT,CAT_CREDIT_CARD,CAT_MORTGAGE,CAT_SAVINGS_ACCOUNT,CAT_DEPENDENTS,CREDIT_SCORE,DEFAULT
0,C02COQEVYU,33269.0,0.0,532304.0,1889.0,0.0,3068.0,0.0,1313.0,4849.0,320.0,3006.0,0.0,17893.0,931.0,33269.0,High,1,0,0,0,0,444,1
1,C02OZKC0ZF,77158.0,91187.0,315648.0,5818.0,0.0,17244.0,0.0,0.0,5224.0,467.0,16339.0,1973.0,20234.0,2845.0,70144.0,No,1,0,0,1,0,625,0
2,C03FHP2D0A,30917.0,21642.0,534864.0,1157.0,0.0,3611.0,36.0,1201.0,4335.0,891.0,2759.0,0.0,16072.0,855.0,30917.0,High,1,0,0,1,0,469,1
3,C03PVPPHOY,80657.0,64526.0,629125.0,6857.0,4402.0,13446.0,0.0,7796.0,4547.0,2068.0,12619.0,1675.0,25038.0,2209.0,80657.0,High,1,0,0,1,0,559,0
4,C04J69MUX0,149971.0,1172498.0,2399531.0,1978.0,0.0,5194.0,0.0,1734.0,34814.0,7513.0,42658.0,3941.0,28167.0,10338.0,136337.0,High,1,1,1,1,1,473,0

In [116]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (2.0.30)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pymysql in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (1.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from sqlalchemy) (4.10.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from sqlalchemy) (3.0.1)

In [117]:
from sqlalchemy import create_engine

In [118]:
user="add your username" 
password= "add your password"
host="localhost"
port="3306"
database="creditscore"

In [119]:
engine=create_engine(f"mysql+pymysql://{user}:{password}@{host}:3306/{database}")
df.to_sql("customers",con=engine,if_exists="replace",index=False)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [120]:
X = df[['CLOTHING', 'EDUCATION', 'ENTERTAINMENT', 'FINES', 'GAMBLING', 'GROCERIES', 'HEALTH', 'HOUSING', 'TAX', 'TRAVEL', 'UTILITIES']]
y = df['EXPENDITURE']

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [121]:
scaler = StandardScaler()

In [122]:
X_train_scaled = scaler.fit_transform(X_train)

In [123]:
X_test_scaled = scaler.transform(X_test)

In [124]:
model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
model.fit(X_train_scaled, y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [125]:
cv_scores = cross_val_score(model, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
cv_rmse_scores = (-cv_scores) ** 0.5
print(f'Cross-Validation RMSE Scores: {cv_rmse_scores}')
print(f'Mean CV RMSE: {cv_rmse_scores.mean()}')

Cross-Validation RMSE Scores: [12762.64004694 12601.81489814 10455.54596868 12568.05939616
 11200.45290095]
Mean CV RMSE: 11917.702642174434

In [129]:
y_pred = model.predict(X_test_scaled)

In [130]:
test_rmse = mean_squared_error(y_test, y_pred, squared=False)
test_r2 = r2_score(y_test, y_pred)
print(f'Test RMSE: {test_rmse}')
print(f'Test R^2: {test_r2}')

Test RMSE: 12504.167444900197
Test R^2: 0.9819774011247513

C:\Users\kevin\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [131]:
importances = model.feature_importances_
feature_names = X.columns

In [132]:
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

print(importance_df)

          Feature  Importance
10      UTILITIES    0.653938
9          TRAVEL    0.181896
8             TAX    0.100957
7         HOUSING    0.032792
5       GROCERIES    0.016580
0        CLOTHING    0.003468
2   ENTERTAINMENT    0.003300
6          HEALTH    0.002540
1       EDUCATION    0.002453
4        GAMBLING    0.001982
3           FINES    0.000095

In [134]:
std_devs = df[['CLOTHING', 'EDUCATION', 'ENTERTAINMENT', 'FINES', 'GAMBLING', 'GROCERIES', 'HEALTH', 'HOUSING', 'TAX', 'TRAVEL', 'UTILITIES']].std()
print("Standard Deviation of Features:\n")
print(std_devs)

Standard Deviation of Features:

CLOTHING          7486.225932
EDUCATION         7065.700350
ENTERTAINMENT    12388.187688
FINES              136.171755
GAMBLING          5007.157570
GROCERIES        19207.309541
HEALTH            5316.800612
HOUSING          17892.426895
TAX               4642.793109
TRAVEL           35822.000110
UTILITIES         6313.708805
dtype: float64

In [11]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (9.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (6.1.1)
Requirement already satisfied: zipp>=3.1.0 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from importlib-resources>=3.2.0->matplotlib) (3.17.0)
Requirement already satisfied: six>=1.5 in c:\users\kevin\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import matplotlib.pyplot as plt

ImportError: DLL load failed while importing _imaging: The specified module could not be found.